# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  set_param synth.incrementalSynthesisCache C:/Users/hjw/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-4788-LAPTOP-481GFMG7/incrSyn
  open_checkpoint openmips_min_sopc_tb_opt.dcp
  set_property webtalk.parent_dir D:/code/fpga/cpu/cpu.cache/wt [current_project]
  implement_debug_core 
  place_design 
  write_checkpoint -force openmips_min_sopc_tb_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file openmips_min_sopc_tb_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file openmips_min_sopc_tb_utilization_placed.rpt -pb openmips_min_sopc_tb_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file openmips_min_sopc_tb_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force openmips_min_sopc_tb_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file openmips_min_sopc_tb_drc_routed.rpt -pb openmips_min_sopc_tb_drc_routed.pb -rpx openmips_min_sopc_tb_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file openmips_min_sopc_tb_methodology_drc_routed.rpt -pb openmips_min_sopc_tb_methodology_drc_routed.pb -rpx openmips_min_sopc_tb_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file openmips_min_sopc_tb_power_routed.rpt -pb openmips_min_sopc_tb_power_summary_routed.pb -rpx openmips_min_sopc_tb_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file openmips_min_sopc_tb_route_status.rpt -pb openmips_min_sopc_tb_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file openmips_min_sopc_tb_timing_summary_routed.rpt -rpx openmips_min_sopc_tb_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file openmips_min_sopc_tb_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file openmips_min_sopc_tb_clock_utilization_routed.rpt"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force openmips_min_sopc_tb_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  catch { write_mem_info -force openmips_min_sopc_tb.mmi }
  write_bitstream -force openmips_min_sopc_tb.bit 
  catch {write_debug_probes -quiet -force openmips_min_sopc_tb}
  catch {file copy -force openmips_min_sopc_tb.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

